Importing the librabries

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

importing classification models


In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

Data Collection and Preprocessing

In [3]:
df= pd.read_csv('./heart.csv')
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [4]:
df.shape

(303, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


For checking missing values present or not in data

In [6]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

Checking the distribution of Target varaible
in this


In [7]:
df['target'].value_counts()

1    165
0    138
Name: target, dtype: int64

1= Defective Heart

0= Healthy Heart

Splitting the features and Target

In [8]:
X= df.drop(columns='target',axis=1)
y=df['target']

In [9]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [10]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

Train test split

In [11]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,stratify=y,random_state=3)

In [12]:
X.shape,X_train.shape,X_test.shape

((303, 13), (242, 13), (61, 13))

Compairing the performance of the model

In [13]:
#LIST of models
models=[LogisticRegression(max_iter=1000),SVC(kernel='linear'),KNeighborsClassifier(n_neighbors=5),RandomForestClassifier()]

In [32]:
def compair():
    for model in models:
        #training the models
        model.fit(X_train,y_train)
        #Evaluating the models
        test_data_prediction=model.predict(X_test)
        
        accuracy=accuracy_score(y_test,test_data_prediction)
        print('Accuarcy score of ',model,'=',accuracy)

In [15]:
compair()

Accuarcy score of  LogisticRegression(max_iter=1000) = 0.7868852459016393
Accuarcy score of  SVC(kernel='linear') = 0.7704918032786885
Accuarcy score of  KNeighborsClassifier() = 0.6557377049180327
Accuarcy score of  RandomForestClassifier() = 0.7704918032786885


# Cross Validation

Logistic Regression

In [16]:
CR_LR=cross_val_score(LogisticRegression(max_iter=1000),X,y,cv=5)

In [17]:
CR_LR

array([0.80327869, 0.86885246, 0.85245902, 0.86666667, 0.75      ])

In [18]:
CR_LR.max()

0.8688524590163934

In [19]:
CR_LR.mean()      #taking mean of all 5 accuracies

0.8282513661202187

In [20]:
CR_LR.mean()

0.8282513661202187

Support Vector Classifier (SVM)

In [21]:
CR_SV=cross_val_score(SVC(kernel='linear'),X,y,cv=5)

In [22]:
CR_SV

array([0.81967213, 0.8852459 , 0.80327869, 0.86666667, 0.76666667])

In [23]:
CR_SV.mean()

0.8283060109289618

KNN

In [24]:
CR_KNN=cross_val_score(KNeighborsClassifier(n_neighbors=5),X,y,cv=5)
CR_KNN

array([0.60655738, 0.6557377 , 0.57377049, 0.73333333, 0.65      ])

Random  Forest

In [28]:
CR_RF=cross_val_score(RandomForestClassifier(n_estimators=200),X,y,cv=5)
CR_RF

array([0.85245902, 0.90163934, 0.80327869, 0.81666667, 0.76666667])

In [29]:
CR_RF.mean()

0.8281420765027322

Compairing the models


In [44]:
models_cr= [LogisticRegression(max_iter=1000),SVC(kernel='linear'),KNeighborsClassifier(n_neighbors=5),RandomForestClassifier(n_estimators=200)]

In [57]:
def compair_cr():
    for model in models_cr:
        cv=cross_val_score(model,X,y,cv=5)
        mean_accuracy=sum(cv)/len(cv)
        mean_accuracy=mean_accuracy*100
        mean_accuracy=round(mean_accuracy,2)
        
        print('Cross validation accuricies for',model,'=',cv)
        print('Mean accuricies',model,'is',mean_accuracy)
        print('................**********..................*************')

In [58]:
compair_cr()

Cross validation accuricies for LogisticRegression(max_iter=1000) = [0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]
Mean accuricies LogisticRegression(max_iter=1000) is 82.83
................**********..................*************
Cross validation accuricies for SVC(kernel='linear') = [0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
Mean accuricies SVC(kernel='linear') is 82.83
................**********..................*************
Cross validation accuricies for KNeighborsClassifier() = [0.60655738 0.6557377  0.57377049 0.73333333 0.65      ]
Mean accuricies KNeighborsClassifier() is 64.39
................**********..................*************
Cross validation accuricies for RandomForestClassifier(n_estimators=200) = [0.83606557 0.8852459  0.80327869 0.78333333 0.75      ]
Mean accuricies RandomForestClassifier(n_estimators=200) is 81.16
................**********..................*************
